services:
  silixe-web:
    image: nginxinc/nginx-unprivileged:stable-alpine
    ports:
      - "80:8080"
    volumes:
      - ./public:/usr/share/nginx/html:ro   # monta tu carpeta local
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
